name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Tag Docker Image"]
    types:
      - success

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to JFrog Artifactory Docker registry
      run: |
        echo "${{ secrets.JF_ACCESS_TOKEN }}" | docker login uhgsaaspoc.jfrog.io --username "token" --password-stdin

    - name: Pull Docker image from Artifactory
      run: |
        docker pull uhgsaaspoc.jfrog.io/python-uhg-docker/python-app:latest

    - name: run the container
      run: |
        echo "Running the container..."

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Configure kubeconfig
    #   run: |
    #     echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f Python-SaaS-PoC/deployment.yml